fix: fix upload repetitive key into the Rafiki
interledger/testnet pull request #1461
Opened 2024-07-31 13:08 UTC by rico191013

### Context

- fixes #1460 

### Changes

2024-07-31 13:10 UTC, Tymmmy commented on packages/wallet/backend/src/walletAddressKeys/service.ts
> +    const isExist = await WalletAddress.query().where({
```suggestion
    const isUploaded = await WalletAddress.query().where({
```

2024-07-31 13:10 UTC, Tymmmy commented on packages/wallet/backend/src/walletAddressKeys/service.ts
> +    if (isExist)
```suggestion
    if (isUploaded)
```

2024-07-31 13:12 UTC, Tymmmy commented on packages/wallet/frontend/src/pages/grant-interactions/index.tsx
> +        : access.limits.receiver ?? null
I think new prettier needs the ()

2024-07-31 13:38 UTC, Tymmmy approved these changes

2024-08-01 14:36 UTC, dragosp1011 approved these changes

2024-08-01 14:38 UTC, dragosp1011 requested changes
please fix failed tests

2024-08-01 19:39 UTC, dragosp1011 approved these changes

2024-08-02 07:42 UTC, Tymmmy approved these changes

2024-08-02 09:57 UTC, merged